steps:
  - label: ":golang: test"
    command:
      - .buildkite/test
    agents:
      queue: build

  - wait

  - label: ":golang: build"
    command:
      - .buildkite/build
    agents:
      queue: build

  - wait

  - label: ":terraform: :mag_right:"
    command:
      - cd terraform/production
      - ../../.buildkite/terraform-validate

  - wait

  - label: ":terraform: :thinking_face:"
    command:
      - cd terraform/production
      - ../../.buildkite/terraform-plan
    concurrency: 1
    concurrency_group: hestia/production/terraform
